[package]
name = "ace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
structopt = "0.3.23"
rand = "0.8.5"
fxhash = "0.2.1"
rustyline = "10.0.0"
rustyline-derive = "0.7.0"